AWSTemplateFormatVersion: '2010-09-09'
Description: Hospital Report Delivery using EC2, VPC, and SNS

Parameters:
  KeyName:
    Description: EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  # -----------------------------
  # VPC
  # -----------------------------
  HospitalVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Hospital-VPC

  # -----------------------------
  # Internet Gateway
  # -----------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HospitalVPC
      InternetGatewayId: !Ref InternetGateway

  # -----------------------------
  # Public Subnet
  # -----------------------------
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HospitalVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  # -----------------------------
  # Route Table
  # -----------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HospitalVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # -----------------------------
  # Security Group
  # -----------------------------
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref HospitalVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # -----------------------------
  # IAM Role for SNS Publish
  # -----------------------------
  EC2SNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2SNSRole

  # -----------------------------
  # SNS Topic
  # -----------------------------
  HospitalSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Hospital-Reports-Topic

  # -----------------------------
  # EC2 Instance
  # -----------------------------
  HospitalEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId:  ami-0c1fe732b5494dc14   # Amazon Linux 2 (change if region differs)
      Tags:
        - Key: Name
          Value: Hospital-EC2

Outputs:
  SNSTopicARN:
    Description: SNS Topic ARN
    Value: !Ref HospitalSNSTopic

  EC2PublicIP:
    Description: EC2 Public IP
    Value: !GetAtt HospitalEC2.PublicIp
